version: 2
jobs:
  update:
    docker:
      - image: circleci/golang:1.11.0
    steps:
      - checkout
      - restore_cache:
          keys:
            # If the exact one isn't found (by sha256 hash) the previous cache
            # key is used. Note, this is filtered to just master below.
            - some-yaml-v1-{{ checksum "some.yaml" }}
            - some-yaml-v1
      - run: ./check.sh
      - save_cache:
          key: some-yaml-v1-{{ checksum "some.yaml" }}
          paths:
            - /tmp/some-yaml-cache

workflows:
  version: 2
  update_prod:
    jobs:
      - update:
          filters:
            branches:
              only:
                - master
