version: 2
jobs:
  build:
    docker:
      - image: debian:9.5
    steps:
      - checkout
      - run: |
          apt-get -y update && apt-get -y install git
          git diff-tree --no-commit-id --name-only -r `echo ${CIRCLE_COMPARE_URL} | cut -d/ -f 7` || true