version: 2
jobs:
  update:
    docker:
      - image: debian:9.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - some-yaml-{{ checksum "some.yaml" }}
      - run: check.sh
      - save_cache:
          key: some-yaml-{{ checksum "some.yaml" }}
          paths:
            - /tmp/some-yaml-cache

workflows:
  version: 2
  update_prod:
    jobs:
      - update:
          filters:
            branches:
              only:
                - master
