version: 2
jobs:
  build:
    docker:
      - image: debian:9.5
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          keys:
            - some-yaml-{{ checksum "some.yaml" }}
      - run: check.sh
      - save_cache:
          key: some-yaml-{{ checksum "some.yaml" }}
          paths:
            - /tmp/some-yaml-cache