version: 2
jobs:
  update:
    docker:
      - image: circleci/golang:1.11.0
    steps:
      - checkout
      - restore_cache:
          keys:
            # Fetch the latest version from the cache rather than a checksum. When
            # the checksom isn't on the end of the key the latest version is fetched.
            - some-yaml-v3
      - run: ./check.sh
      - save_cache:
          # Save with sha256 checksum in cache key to identify each unique change
          key: some-yaml-v3-{{ checksum "some.yaml" }}
          paths:
            - /tmp/some-yaml-cache

workflows:
  version: 2
  update_prod:
    jobs:
      - update:
          filters:
            branches:
              only:
                - master
